# Generated by Django 5.0.4 on 2024-04-25 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='in_list',
        ),
    ]
