# Generated by Django 5.0.4 on 2024-04-26 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_item_in_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rank',
            field=models.TextField(null=True),
        ),
    ]
