# Generated by Django 5.0.4 on 2024-04-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_src',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='image_src',
            field=models.TextField(null=True),
        ),
    ]
