# Generated by Django 5.0.4 on 2024-04-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_item_image_src_list_image_src'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
