# Generated by Django 5.0.4 on 2024-04-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rank',
            field=models.TextField(),
        ),
    ]
