# Generated by Django 5.0.4 on 2024-04-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_item_image_src_remove_list_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.TextField(),
        ),
    ]
