# Generated by Django 5.0.4 on 2024-04-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='thumbnail',
            field=models.TextField(),
        ),
    ]
