# Generated by Django 5.0.4 on 2024-04-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
