# Generated by Django 5.0.3 on 2024-03-13 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='user',
        ),
    ]
