# Generated by Django 5.0.3 on 2024-03-13 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_user_id_session_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='user_id',
            new_name='user',
        ),
    ]
